apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: spring-apps
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Spring Applications Project
  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'
  # No restrictions on destinations for this example
  destinations: 
  - namespace: spring-apps-dev  
    server: 'https://kubernetes.default.svc'
  # Allow all cluster-scoped resources to be created
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  # Allow all namespaced-scoped resources to be created, except for ResourceQuota, LimitRange, NetworkPolicy
  namespaceResourceBlacklist:
  - group: ''
    kind: ResourceQuota
  - group: ''
    kind: LimitRange
  - group: ''
    kind: NetworkPolicy
  # Allow all namespaced-scoped resources to be created
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  roles:
  # A role which provides read-only access to all applications in the project for the user 'guest'
  - name: read-only
    description: Read-only privileges to spring-apps
    policies:
    - p, proj:spring-apps:read-only, applications, get, spring-apps/*, allow
    groups:
    - guest
  # A role which provides sync privileges to only the guestbook-dev application for the user 'deploy-agent'
  - name: synconly-role
    description: Sync-only privileges for guestbook-dev
    policies:
    - p, proj:spring-apps:synconly-role, applications, sync, spring-apps/guestbook-dev, allow
    groups:
    - deploy-agent
  # A role which provides manager privileges for the user 'mahdi'
  - name: manager-role
    description: Manager privileges for spring-apps
    policies:
    - p, proj:spring-apps:manager-role, applications, '*', '*', allow
    groups:
    - mahdi

