appProjects:
  - name: spring-apps
    description: 'Spring Applications Project'
    sourceRepos:
    - '*'
    namespaces: 
    - spring-apps-dev 
    managerGroups:
    - mahdi
    syncOnlyGroups:
    readOnlyGroups:
    - guest

applications:
  - name: bluegreen
    namespace: argocd
    project: default
    repoURL: https://github.com/argoproj/rollouts-demo.git
    targetRevision: HEAD
    path: examples/blue-green
    destination:
      server: https://kubernetes.default.svc
      namespace: rollouts
    syncOptions:
      - CreateNamespace=true 
    automated:
      selfHeal: true
      prune: true
  - name: helmargo
    namespace: argocd
    labels:
      type: helm
      namespace: spring-apps-dev
    project: spring-apps
    repoURL: https://github.com/mkonzali/DemoHelmChart.git
    targetRevision: HEAD
    path: .
    helm:
      releaseName: helmargo
      skipCrds: true
      valueFiles:
        - values.yaml
        - dev-values.yaml
      parameters:
        - name: image.tag
          value: 1.0.0
    ignoreDifferences:
      - group: apps
        kind: Deployment
        jsonPointers:
          - /spec/replicas
    destination:
      server: https://kubernetes.default.svc
      namespace: spring-apps-dev
    syncOptions:
      - CreateNamespace=true 
    automated:
      selfHeal: true
      prune: true
  - name: demoargo
    namespace: argocd
    project: default
    repoURL: https://github.com/mkonzali/DemoManifests.git
    targetRevision: work
    path: demoargo
    destination:
      server: https://kubernetes.default.svc
      namespace: spring-apps-dev
    syncOptions:
      - CreateNamespace=true 
    automated:
      selfHeal: true
      prune: true
